version: "3.9"
services:
  moni-pro-port:
    image: aman7ph/moni-pro-port:latest
    container_name: moni-pro-port
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - moni-pro-net
    restart: always
networks:
  moni-pro-net:
    external: true
