# This is a GitHub Actions workflow file for CI/CD of a React application using Vite.
# It builds the project and sends notifications to a Slack channel upon completion.
name: React + Vite CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  notify:
    name: Notify Team
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send Slack Notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          JOB_STATUS: ${{ job.status }}
        run: |
          if [ "$JOB_STATUS" == "success" ]; then
            STATUS_MESSAGE="✅ CI Passed on branch ${{ github.ref_name }}"
          else
            STATUS_MESSAGE="❌ CI Failed on branch ${{ github.ref_name }}"
          fi

          curl -X POST -H 'Content-type: application/json' --data "{
            \"text\": \"*${{ github.repository }}*: $STATUS_MESSAGE\n🔁 Commit: ${{ github.sha }}\n🔗 PR/Push: ${{ github.event.pull_request.html_url || github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}\"
          }" $SLACK_WEBHOOK_URL
